"""Add CRR tables

Revision ID: 64f9b1d61e03
Revises: 3980edabfb38
Create Date: 2024-11-25 14:04:19.494959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '64f9b1d61e03'
down_revision = '3980edabfb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crr_merton',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('cds_period', sa.Integer(), nullable=False),
    sa.Column('cds_delta', sa.Float(), nullable=True),
    sa.Column('ps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_date', 'cds_period')
    )
    op.create_table('crr_securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker_bbg', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_bbg')
    )
    op.create_table('cds_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['crr_securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crr_portfolio_constituents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['crr_securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'security_id')
    )
    op.create_index(op.f('ix_crr_portfolio_constituents_user_id'), 'crr_portfolio_constituents', ['user_id'], unique=False)
    op.create_table('crr_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['crr_securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crr_prices')
    op.drop_index(op.f('ix_crr_portfolio_constituents_user_id'), table_name='crr_portfolio_constituents')
    op.drop_table('crr_portfolio_constituents')
    op.drop_table('cds_prices')
    op.drop_table('crr_securities')
    op.drop_table('crr_merton')
    # ### end Alembic commands ###
