"""Add MRIPortfolio and related models

Revision ID: d94cc842e815
Revises: 1a31ce608336
Create Date: 2024-11-24 16:45:44.666889

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd94cc842e815'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mri_asset_outputs',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('asset_class', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rpr', sa.Float(), nullable=False),
    sa.Column('lookback', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('mri_portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mri_portfolios_name'), 'mri_portfolios', ['name'], unique=False)
    op.create_index(op.f('ix_mri_portfolios_user_id'), 'mri_portfolios', ['user_id'], unique=False)
    op.create_table('mri_portfolio_constituents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('asset_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('asset_class', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['mri_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mri_portfolio_constituents')
    op.drop_index(op.f('ix_mri_portfolios_user_id'), table_name='mri_portfolios')
    op.drop_index(op.f('ix_mri_portfolios_name'), table_name='mri_portfolios')
    op.drop_table('mri_portfolios')
    op.drop_table('mri_asset_outputs')
    # ### end Alembic commands ###
